import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const municipalities = [
  { name: 'Vitória', lat: -20.3155, lng: -40.3128, region: 'Região Imediata de Vitória' },
  { name: 'Vila Velha', lat: -20.3297, lng: -40.2925, region: 'Região Imediata de Vitória' },
  { name: 'Serra', lat: -20.1287, lng: -40.3075, region: 'Região Imediata de Vitória' },
  { name: 'Cariacica', lat: -20.2619, lng: -40.4177, region: 'Região Imediata de Vitória' },
  { name: 'Guarapari', lat: -20.6686, lng: -40.4988, region: 'Região Imediata de Vitória' },
  { name: 'Viana', lat: -20.3909, lng: -40.5619, region: 'Região Imediata de Vitória' },
  { name: 'Anchieta', lat: -20.8056, lng: -40.6414, region: 'Região Imediata de Vitória' },
  { name: 'Fundão', lat: -19.9361, lng: -40.4067, region: 'Região Imediata de Vitória' },
  { name: 'Alfredo Chaves', lat: -20.6369, lng: -40.7536, region: 'Região Imediata de Vitória' },
  { name: 'Piúma', lat: -20.8458, lng: -40.7278, region: 'Região Imediata de Vitória' },
  { name: 'São Mateus', lat: -18.7157, lng: -39.8578, region: 'Região Imediata de São Mateus' },
  { name: 'Conceição da Barra', lat: -18.4974, lng: -39.7394, region: 'Região Imediata de São Mateus' },
  { name: 'Jaguaré', lat: -18.9642, lng: -40.1617, region: 'Região Imediata de São Mateus' },
  { name: 'Boa Esperança', lat: -18.5528, lng: -40.5972, region: 'Região Imediata de São Mateus' },
  { name: 'Montanha', lat: -18.1319, lng: -40.5378, region: 'Região Imediata de São Mateus' },
  { name: 'Mucurici', lat: -18.1461, lng: -40.2286, region: 'Região Imediata de São Mateus' },
  { name: 'Pedro Canário', lat: -18.0378, lng: -40.6581, region: 'Região Imediata de São Mateus' },
  { name: 'Pinheiros', lat: -18.4173, lng: -40.2155, region: 'Região Imediata de São Mateus' },
  { name: 'Ponto Belo', lat: -18.4269, lng: -40.4761, region: 'Região Imediata de São Mateus' },
  { name: 'Colatina', lat: -19.5396, lng: -40.6306, region: 'Região Imediata de Colatina' },
  { name: 'Baixo Guandu', lat: -19.0611, lng: -41.0139, region: 'Região Imediata de Colatina' },
  { name: 'São Gabriel da Palha', lat: -18.7178, lng: -40.5375, region: 'Região Imediata de Colatina' },
  { name: 'Marilândia', lat: -19.4092, lng: -40.4814, region: 'Região Imediata de Colatina' },
  { name: 'Governador Lindenberg', lat: -19.1867, lng: -40.7394, region: 'Região Imediata de Colatina' },
  { name: 'Águia Branca', lat: -18.9822, lng: -40.9444, region: 'Região Imediata de Colatina' },
  { name: 'Alto Rio Novo', lat: -19.0592, lng: -40.8189, region: 'Região Imediata de Colatina' },
  { name: 'Mantenópolis', lat: -18.8622, lng: -41.1303, region: 'Região Imediata de Colatina' },
  { name: 'Pancas', lat: -18.4386, lng: -40.9611, region: 'Região Imediata de Colatina' },
  { name: 'São Domingos do Norte', lat: -19.1778, lng: -40.5956, region: 'Região Imediata de Colatina' },
  { name: 'São Roque do Canaã', lat: -19.3033, lng: -40.6406, region: 'Região Imediata de Colatina' },
  { name: 'Vila Valério', lat: -18.9464, lng: -40.7908, region: 'Região Imediata de Colatina' },
  { name: 'Itaguaçu', lat: -19.5508, lng: -40.8572, region: 'Região Imediata de Colatina' }
];

const entities = [
  {
    name: 'Associação Cultural Manguari',
    type: 'associacao_cultural',
    category: 'Dança',
    municipality: 'Vitória',
    region: 'Região Imediata de Vitória',
    lat: -20.3155,
    lng: -40.3128,
    address: 'Rua da Passagem, 123 - Centro',
    phone: '(27) 3322-4455',
    email: 'contato@manguari.org.br',
    description: 'Grupo de dança tradicional capixaba, preservando a cultura do boi-bumbá e ciranda.',
    services: 'Aulas de dança, apresentações, oficinas',
    foundedYear: 2005,
    status: 'active'
  },
  {
    name: 'Rádio Comunitária FM Serra',
    type: 'radio_comunitaria',
    category: 'Educação',
    municipality: 'Serra',
    region: 'Região Imediata de Vitória',
    lat: -20.1287,
    lng: -40.3075,
    address: 'Av. Brasil, 500 - Serra',
    phone: '(27) 3258-1100',
    email: 'radio@serra.fm.br',
    description: 'Rádio comunitária promotora de cultura e informação local.',
    services: 'Transmissão de programas culturais, noticias comunitárias',
    foundedYear: 2002,
    status: 'active'
  },
  {
    name: 'Centro Cultural Sementeira',
    type: 'ponto_cultura',
    category: 'Cultura Popular',
    municipality: 'Vila Velha',
    region: 'Região Imediata de Vitória',
    lat: -20.3297,
    lng: -40.2925,
    address: 'Rua Sete de Setembro, 78 - Centro',
    phone: '(27) 3289-2233',
    email: 'sementeira@cultura.es.gov.br',
    description: 'Ponto de Cultura reconhecido pelo MinC, trabalhando com capoeira e cultura popular.',
    services: 'Aulas de capoeira, oficina de percussão, ciranda',
    foundedYear: 2008,
    status: 'active'
  },
  {
    name: 'Cineclube Guapurux',
    type: 'cineclube',
    category: 'Cinema',
    municipality: 'Cachoeiro de Itapemirim',
    region: 'Sul do ES',
    lat: -20.8486,
    lng: -41.1129,
    address: 'Rua 25 de Março, 150 - Centro',
    phone: '(28) 3522-0077',
    email: 'cineclube.guapurux@gmail.com',
    description: 'Cineclube que promove sessões de cinema brasileiro e independent.',
    services: 'Sessões de cinema, debates, mostras',
    foundedYear: 2015,
    status: 'active'
  },
  {
    name: 'Coletivo Hip Hop Sul Capixaba',
    type: 'artista_coletivo',
    category: 'Hip Hop',
    municipality: 'Cachoeiro de Itapemirim',
    region: 'Sul do ES',
    lat: -20.8500,
    lng: -41.1150,
    address: 'Rua das Laranjeiras, 45 - Ferroviários',
    phone: '(28) 99988-1122',
    email: 'hiphopsules@gmail.com',
    description: 'Coletivo de rap, breakdance e grafite da região sul.',
    services: 'Oficinas de rap, break, grafite; eventos culturais',
    foundedYear: 2012,
    status: 'active'
  },
  {
    name: 'Associação de Artesãos de Anchieta',
    type: 'associacao_cultural',
    category: 'Artesanato',
    municipality: 'Anchieta',
    region: 'Região Imediata de Vitória',
    lat: -20.8056,
    lng: -40.6414,
    address: 'Praça da Bandeira, s/n - Centro',
    phone: '(28) 3536-0100',
    email: 'artesanato.anchieta@yahoo.com.br',
    description: 'Associação que valoriza o artesanato local, especialmente palha e crochê.',
    services: 'Comercialização de artesanato, cursos',
    foundedYear: 2009,
    status: 'active'
  },
  {
    name: 'Rádio Comunitária Norte Capixaba',
    type: 'radio_comunitaria',
    category: 'Informação',
    municipality: 'São Mateus',
    region: 'Região Imediata de São Mateus',
    lat: -18.7157,
    lng: -39.8578,
    address: 'Av. Getúlio Vargas, 890 - Centro',
    phone: '(27) 3762-3300',
    email: 'radiocomunitarianorte@gmail.com',
    description: 'Rádio comunitária que divulga a cultura e notícias do norte do estado.',
    services: 'Informação, cultura, educação',
    foundedYear: 2003,
    status: 'active'
  },
  {
    name: 'Teatro Experimental de Linhares',
    type: 'associacao_cultural',
    category: 'Teatro',
    municipality: 'Linhares',
    region: 'Norte do ES',
    lat: -19.3908,
    lng: -40.0723,
    address: 'Rua das Rosas, 22 - Centro',
    phone: '(27) 3264-5544',
    email: 'telinc@yahoo.com.br',
    description: 'Grupo de teatro amador que promove peças locais e regionais.',
    services: 'Apresentações de teatro, oficinas de dramaturgia',
    foundedYear: 2007,
    status: 'active'
  },
  {
    name: 'Ponto de Cultura Batuque',
    type: 'ponto_cultura',
    category: 'Música',
    municipality: 'Guarapari',
    region: 'Região Imediata de Vitória',
    lat: -20.6686,
    lng: -40.4988,
    address: 'Rua da Praia, 100 - Meaípe',
    phone: '(27) 3362-7700',
    email: 'batuque.pontocultura@gmail.com',
    description: 'Ponto de Cultura que valoriza a música de batucada e percussão.',
    services: 'Aulas de percussão, grupos de batucada, eventos',
    foundedYear: 2010,
    status: 'active'
  },
  {
    name: 'Associação Folclórica de Domingos Martins',
    type: 'associacao_cultural',
    category: 'Patrimônio Cultural',
    municipality: 'Domingos Martins',
    region: 'Serrana',
    lat: -20.3633,
    lng: -40.6628,
    address: 'Centro Cultural - Distrito de Melgaço',
    phone: '(27) 3268-1155',
    email: 'folcloredom@hotmail.com',
    description: 'Preservação das tradições folclóricas e indígenas da região serrana.',
    services: 'Apresentações folclóricas, museologia, oficinas',
    foundedYear: 1998,
    status: 'active'
  },
  {
    name: 'Cineclube de Nova Venécia',
    type: 'cineclube',
    category: 'Cinema',
    municipality: 'Nova Venécia',
    region: 'Central',
    lat: -18.7105,
    lng: -40.4038,
    address: 'Rua do Cine, 15 - Centro',
    email: 'cineclube.nv@outlook.com',
    description: 'Cineclube que promove o cinema independente no norte capixaba.',
    services: 'Sessões de filmes, workshop de cinema',
    foundedYear: 2018,
    status: 'active'
  },
  {
    name: 'Coletivo de Artes Visuais Porto',
    type: 'artista_coletivo',
    category: 'Artes Visuais',
    municipality: 'Vitória',
    region: 'Região Imediata de Vitória',
    lat: -20.3200,
    lng: -40.3200,
    address: 'Ilha do Boneco, 45 - Centro',
    phone: '(27) 3222-0099',
    email: 'coletivoporto.art@gmail.com',
    description: 'Coletivo de artistas plásticos e grafiteiros.',
    services: 'Exposições, mural vivo, oficinas de arte',
    foundedYear: 2016,
    status: 'active'
  },
  {
    name: 'Associação de Capoeira Beribape',
    type: 'associacao_cultural',
    category: 'Capoeira',
    municipality: 'Cariacica',
    region: 'Região Imediata de Vitória',
    lat: -20.2619,
    lng: -40.4177,
    address: 'Rua da Liberdade, 200 - Campo Belo',
    phone: '(27) 3226-8833',
    email: 'capoeira.beribape@yahoo.com.br',
    description: 'Associação de capoeira com tradição em maculele e ciranda.',
    services: 'Aulas de capoeira, maculele, percussão',
    foundedYear: 2001,
    status: 'active'
  },
  {
    name: 'Rádio FM Esperança',
    type: 'radio_comunitaria',
    category: 'Educação',
    municipality: 'Colatina',
    region: 'Região Imediata de Colatina',
    lat: -19.5396,
    lng: -40.6306,
    address: 'Av. Pres. Getúlio Vargas, 1200 - Centro',
    phone: '(27) 3712-9900',
    email: 'fmesperanca@colatina.es.gov.br',
    description: 'Rádio educativa comunitária da região central.',
    services: 'Programação educativa e cultural',
    foundedYear: 2006,
    status: 'active'
  },
  {
    name: 'Associação de Quadrilha Junina de Marataízes',
    type: 'associacao_cultural',
    category: 'Dança',
    municipality: 'Marataízes',
    region: 'Sul do ES',
    lat: -21.0404,
    lng: -40.8333,
    address: 'Praça da Igreja, s/n - Centro',
    phone: '(28) 3534-2200',
    email: 'quadrilhamarataizes@gmail.com',
    description: 'Promove a tradição das quadrilhas juninas no sul do estado.',
    services: 'Aulas de quadrilha, ensaios, apresentações',
    foundedYear: 2004,
    status: 'active'
  },
  {
    name: 'Ponto de Cultura Quilombinho',
    type: 'ponto_cultura',
    category: 'Cultura Popular',
    municipality: 'Aracruz',
    region: 'Norte do ES',
    lat: -19.8225,
    lng: -40.2738,
    address: 'Comunidade Quilombola - Barra do Sahy',
    phone: '(27) 3256-7700',
    email: 'quilombinho.aracruz@gmail.com',
    description: 'Ponto de Cultura que preserva a tradição quilombola.',
    services: 'Cultura quilombola, artesanato, dança',
    foundedYear: 2011,
    status: 'active'
  },
  {
    name: 'Banda Filarmônica 24 de Maio',
    type: 'associacao_cultural',
    category: 'Música',
    municipality: 'Cachoeiro de Itapemirim',
    region: 'Sul do ES',
    lat: -20.8450,
    lng: -41.1100,
    address: 'Rua da Concência, 05 - Centro',
    phone: '(28) 3521-3344',
    email: 'filarmonica24demaio@gmail.com',
    description: 'Banda filarmônica com tradição em música clássica e populares.',
    services: 'Concertos, desfiles, eventos',
    foundedYear: 1875,
    status: 'active'
  },
  {
    name: 'Coletivo Teatro do Absurdo',
    type: 'artista_coletivo',
    category: 'Teatro',
    municipality: 'Serra',
    region: 'Região Imediata de Vitória',
    lat: -20.1300,
    lng: -40.3050,
    address: 'Rua da Criatividade, 33 - Feu Rosa',
    email: 'teatro.absurdo.serra@gmail.com',
    description: 'Coletivo de teatro experimental e performances.',
    services: 'Espetáculos, intervenções urbanas, oficina',
    foundedYear: 2019,
    status: 'active'
  },
  {
    name: 'Associação de Teatro de Guarapari',
    type: 'associacao_cultural',
    category: 'Teatro',
    municipality: 'Guarapari',
    region: 'Região Imediata de Vitória',
    lat: -20.6700,
    lng: -40.5000,
    address: 'Av. Oceânica, 800 - Centro',
    phone: '(27) 3361-5500',
    email: 'ateoguara@yahoo.com.br',
    description: 'Grupo de teatro amador com produções locais.',
    services: 'Péças de teatro, oficinas',
    foundedYear: 2013,
    status: 'active'
  },
  {
    name: 'Rádio Comunitária Pedra Azul',
    type: 'radio_comunitaria',
    category: 'Entretenimento',
    municipality: 'Domingos Martins',
    region: 'Serrana',
    lat: -20.3650,
    lng: -40.6650,
    address: 'Centro da Cidade - Distrito de Pedra Azul',
    phone: '(27) 3268-3300',
    email: 'radiopedraazul@gmail.com',
    description: 'Rádio comunitária da região serrana.',
    services: 'Música, informação local',
    foundedYear: 2010,
    status: 'active'
  },
  {
    name: 'Instituto de Cultura Indígena',
    type: 'associacao_cultural',
    category: 'Patrimônio Cultural',
    municipality: 'São Mateus',
    region: 'Região Imediata de São Mateus',
    lat: -18.7200,
    lng: -39.8600,
    address: 'Terra Indígena - Comboios',
    phone: '(27) 3763-1100',
    email: 'instituto.indigena@gmail.com',
    description: 'Instituto dedicado à preservação da cultura indígena.',
    services: 'Cultura, artesanato, educação',
    foundedYear: 2000,
    status: 'active'
  },
  {
    name: 'Associação de Escritores do ES',
    type: 'associacao_cultural',
    category: 'Literatura',
    municipality: 'Vitória',
    region: 'Região Imediata de Vitória',
    lat: -20.3180,
    lng: -40.3150,
    address: 'Rua das Artes, 150 - Santa Lucia',
    phone: '(27) 3221-7744',
    email: 'escritores.es@gmail.com',
    description: 'Associação que promove a literatura capixaba.',
    services: 'Feiras de livro, saraus, lançamentos',
    foundedYear: 1995,
    status: 'active'
  },
  {
    name: 'Cineclube Itinerante Vale do Rio Doce',
    type: 'cineclube',
    category: 'Cinema',
    municipality: 'Colatina',
    region: 'Região Imediata de Colatina',
    lat: -19.5420,
    lng: -40.6330,
    address: 'Circula por toda a região',
    phone: '(27) 3712-4455',
    email: 'cineclube.itinerante@gmail.com',
    description: 'Cineclube ambulante que leva cinema às comunidades.',
    services: 'Sessões itinerantes, educação audiovisual',
    foundedYear: 2017,
    status: 'active'
  },
  {
    name: 'Associação de DJs e Produtores',
    type: 'artista_coletivo',
    category: 'Música',
    municipality: 'Vila Velha',
    region: 'Região Imediata de Vitória',
    lat: -20.3320,
    lng: -40.2950,
    address: 'Rua da Música, 77 - Cobilândia',
    email: 'djsprodutoresvv@gmail.com',
    description: 'Coletivo de DJs e produtores musicais.',
    services: 'Eventos, productions, oficinas de DJ',
    foundedYear: 2014,
    status: 'active'
  },
  {
    name: 'Grupo de Choro e Samba de Cariacica',
    type: 'associacao_cultural',
    category: 'Música',
    municipality: 'Cariacica',
    region: 'Região Imediata de Vitória',
    lat: -20.2650,
    lng: -40.4200,
    address: 'Rua do Samba, 12 - Nova Rosa da Penha',
    phone: '(27) 3226-1122',
    email: 'chorosamba.cariacica@gmail.com',
    description: 'Grupo que preserva o choro e samba de raiz.',
    services: 'Rodeios de choro, eventos, oficinas',
    foundedYear: 2008,
    status: 'active'
  }
];

async function seed() {
  console.log('Seeding database...');

  await prisma.entity.deleteMany();
  await prisma.municipality.deleteMany();

  console.log('Cleared existing data');

  for (const mun of municipalities) {
    await prisma.municipality.create({ data: mun });
  }
  console.log(`Created ${municipalities.length} municipalities`);

  for (const entity of entities) {
    await prisma.entity.create({ data: entity });
  }
  console.log(`Created ${entities.length} entities`);

  const count = await prisma.entity.count();
  console.log(`Total entities in database: ${count}`);
}

seed()
  .catch(console.error)
  .finally(() => prisma.$disconnect());